### ISSUE TITLE
org-review-insert-next-review lacks day of week

### ISSUE THREAD

**Issue by bitozoid** [brabalan/org-review#6]
This is a minor issue.

When inserting the next review via `org-review-insert-next-review`, the `NEXT_REVIEW` property is set with the new date, but the day of the week is missing.

I would add the day of the week for coherence.

**Comment by brabalan** [comment]
I just pushed a change that should do that. Could you please check that it works for you?

**Comment by bitozoid** [comment]
@brabalan It works for me.

Thanks a lot!
